apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-conf
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ (.Files.Glob "config/*").AsConfig | indent 2 }}
