name: apache
version: 2.1.2
appVersion: 2.4.37
description: Chart for Apache HTTP Server
keywords:
- apache
- http
- https
- www
- web
- reverse proxy
home: https://httpd.apache.org
sources:
- https://github.com/bitnami/bitnami-docker-apache
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
